name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Checkout theos/theos
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Build
        run: |
          export THEOS=theos

          git submodule init
          git submodule update
          gmake package FINALPACKAGE=1 STRIP=0
          cd packages && mv *.ipa "`basename *.ipa .ipa`.tipa"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: artifact
          path: packages/*.tipa
